name: cspell-action
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - uses: streetsidesoftware/cspell-action@v1.1.2
